apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.appName }}
  name: {{ .Values.serviceName }}
spec:
  ports:
  - port: {{ .Values.sourcePort }}
    protocol: TCP
    targetPort: 8080
  selector:
    app: {{ .Values.appName }}